---
apiVersion: v1
kind: Pod
metadata:
  name: kafka2
  labels:
    app: kfk
    category: kafka
    instance: "2"
spec:
  containers:
  - name: confluent-kafka
    imagePullPolicy: Always 
    image: mbe1224/confluent-kafka
    env:
    - name: KAFKA_BROKER_ID
      value: "2"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka2:9092"