---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zk
  namespace: confluent-platform  
  labels:
    category: zookeeper
spec: 
  serviceName: zk-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: zk
    spec: 
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - zk
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: confluent-zookeeper
        imagePullPolicy: Always
        image: mbe1224/confluent-zookeeper
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name: ZOOKEEPER_TICK_TIME
          valueFrom:
            configMapKeyRef:
                name: zk-cm
                key: tickTime
        - name: ZOOKEEPER_INIT_LIMIT
          valueFrom:
            configMapKeyRef:
                name: zk-cm
                key: initLimit
        - name: ZOOKEEPER_SYNC_LIMIT
          valueFrom:
            configMapKeyRef:
                name: zk-cm
                key: syncLimit
        - name: ZOOKEEPER_MAX_CLIENT_CNXNS
          valueFrom:
            configMapKeyRef:
                name: zk-cm
                key: maxClientCnxns
        - name: ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT
          valueFrom:
            configMapKeyRef:
                name: zk-cm
                key: autopurge.snapRetainCount
        - name: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
          valueFrom:
            configMapKeyRef:
                name: zk-cm
                key: autopurge.purgeInterval
        - name: ZOOKEEPER_LOG4J_ROOT_LOGLEVEL
          valueFrom:
            configMapKeyRef:
                name: zk-cm
                key: log4j.root.loglevel
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_SERVER_PORT
          value: "2888"
        - name: ZOOKEEPER_ELECTION_PORT
          value: "3888"
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - '[ "imok" = "$(echo ruok | nc -w 1 -q 1 127.0.0.1 2181)" ]'            
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - '[ "imok" = "$(echo ruok | nc -w 1 -q 1 127.0.0.1 2181)" ]' 
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi