---
version: '3'
services:
  zk-1:
    image: mbe1224/confluent-zookeeper
    ports:
      - "12181:12181"
      - "12888:12888"
      - "13888:13888" 
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_SERVERS: localhost:12888:13888;localhost:22888:23888;localhost:32888:33888
    network_mode: host        

  zk-2:
    image: mbe1224/confluent-zookeeper
    ports:
      - "22181:22181"
      - "22888:22888"
      - "23888:23888"         
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_SERVERS: localhost:12888:13888;localhost:22888:23888;localhost:32888:33888
    network_mode: host  

  zk-3:
    image: mbe1224/confluent-zookeeper
    ports:
      - "32181:32181"
      - "32888:32888"
      - "33888:33888"           
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_SERVERS: localhost:12888:13888;localhost:22888:23888;localhost:32888:33888
    network_mode: host        
...