---
apiVersion: v1
kind: Service
metadata:
  name: rp-svc
  labels:
    app: rp-svc
    category: rest-proxy    
spec:
  ports:
  - name: server
    protocol: TCP  
    port: 8082
  clusterIP: None        
  selector:
    app: rp