---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: rp-pdb
  namespace: confluent-platform
  labels:
    category: rest-proxy
spec:
  selector:
    matchLabels:
      app: rp
  minAvailable: 1