---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper1
  labels:
    app: zk
    category: zookeeper
    instance: "1"
spec:
  containers:
  - name: confluent-zookeeper
    imagePullPolicy: Always 
    image: mbe1224/confluent-zookeeper
    env:
    - name: ZOOKEEPER_SERVER_ID
      value: "1"
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"
    - name: ZOOKEEPER_TICK_TIME
      value: "2000"
    - name: ZOOKEEPER_INIT_LIMIT
      value: "5"
    - name: ZOOKEEPER_SYNC_LIMIT
      value: "2"
    - name: ZOOKEEPER_SERVERS
      value: "zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888"