---
apiVersion: v1
kind: Pod
metadata:
  name: rest-proxy1
  labels:
    app: rp
    category: rest-proxy
    instance: "1"       
spec:
  containers:
  - name: rest-proxy
    imagePullPolicy: Always 
    image: mbe1224/confluent-rest-proxy
    env:
    - name: KAFKA_REST_ZOOKEEPER_CONNECT
      value: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    - name: KAFKA_REST_SCHEMA_REGISTRY_URL
      value: "schema-registry1:8081"
    - name: KAFKA_REST_HOST_NAME
      value: "rest-proxy1"
    - name: KAFKA_REST_LISTENERS
      value: "http://rest-proxy1:8082"
    readinessProbe:
      tcpSocket:
        port: 8082
      initialDelaySeconds: 10        
      timeoutSeconds: 1
    livenessProbe:
      tcpSocket:
        port: 8082
      initialDelaySeconds: 10        
      timeoutSeconds: 1         