---
version: '3'
services:
  zk:
    image: mbe1224/confluent-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    network_mode: host    

  kfk:
    image: mbe1224/confluent-kafka
    depends_on:
      - zk
    ports:
      - "9092:9092"      
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    network_mode: host         
...