---
apiVersion: v1
kind: Service
metadata:
  name: rest-proxy1
  labels:
    app: rp
    category: rest-proxy    
spec:
  ports:
  - name: server
    protocol: TCP  
    port: 8082
  selector:
    app: rp
    instance: "1"