---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry1
  labels:
    app: sr
    category: schema-registry
spec:
  ports:
  - name: server
    protocol: TCP  
    port: 8081
  selector:
    app: sr
    instance: "1"