---
version: '3'
services:
  zk:
    image: mbe1224/confluent-osp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    network_mode: host

  kfk:
    image: mbe1224/confluent-osp-kafka
    depends_on:
      - zk
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    network_mode: host

  sr:
    image: mbe1224/confluent-osp-schema-registry
    depends_on:
      - zk
      - kfk
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: confluent-osp-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: localhost:2181
      SCHEMA_REGISTRY_LISTENERS: http://localhost:8081
    network_mode: host
    
  rp:
    image: mbe1224/confluent-osp-rest-proxy
    depends_on:
      - zk
      - kfk
      - sr
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: confluent-osp-rest-proxy    
      KAFKA_REST_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_REST_LISTENERS: http://localhost:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://localhost:8081
    network_mode: host      
...